# Generated by Django 3.0.8 on 2020-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('postalcode', models.IntegerField(max_length=250)),
                ('phone', models.IntegerField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.IntegerField(max_length=250)),
                ('dateentered', models.DateTimeField(max_length=250)),
            ],
        ),
    ]
