# Generated by Django 3.0.8 on 2020-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=250, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
