# Generated by Django 3.0.8 on 2020-08-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_supplier',
        ),
    ]
