<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-08-23 11:32
=======
# Generated by Django 3.0.8 on 2020-08-29 08:41
>>>>>>> 19aa3f56c37c1454802fcf1abc3f3c030dc72173
=======
# Generated by Django 3.0.8 on 2020-08-23 11:32
>>>>>>> 9e748a70e9c8fd037cc4ddc1e3a3b49d51c7225c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('content', '0001_initial'),
        ('accounts', '0001_initial'),
=======
        ('accounts', '0001_initial'),
        ('content', '__first__'),
>>>>>>> 19aa3f56c37c1454802fcf1abc3f3c030dc72173
=======
        ('content', '0001_initial'),
        ('accounts', '0001_initial'),
>>>>>>> 9e748a70e9c8fd037cc4ddc1e3a3b49d51c7225c
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
    ]
