# Generated by Django 3.0.8 on 2020-08-11 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0002_product_supplier_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_supplier',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_supplier',
            name='supplier_id',
        ),
        migrations.RenameModel(
            old_name='Supplier_Profile',
            new_name='SupplierProfile',
        ),
    ]
