# Generated by Django 3.0.8 on 2020-08-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_product_unit_price'),
        ('cart', '0003_auto_20200811_1132'),
        ('Supplier', '0003_auto_20200811_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Supplier',
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Product'),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierProfile'),
        ),
    ]
