# Generated by Django 3.0.8 on 2020-08-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20200809_1205'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('product_supplier_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Product_Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Delivery'),
        ),
    ]
