# Generated by Django 3.0.8 on 2020-08-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_auto_20200811_1132'),
        ('cart', '0002_auto_20200810_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('u', 'Unfinilized'), ('f', 'Finalized')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_supplier_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Supplier.ProductSupplier'),
        ),
    ]
