# Generated by Django 3.0.8 on 2020-08-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200811_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.Cart'),
        ),
    ]
