# Generated by Django 3.0.8 on 2020-08-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_auto_20200811_1132'),
        ('cart', '0004_auto_20200820_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Supplier.ProductSupplier'),
        ),
    ]
