# Generated by Django 3.0.8 on 2020-08-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='content/images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='content.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('INT', 'Integer'), ('TXT', 'Text'), ('BOOL', 'Bool')], max_length=4)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, max_length=250, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_attr', to='content.Attribute')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_attr', to='content.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(through='content.ProductAttr', to='content.Attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.SubCategory'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('rate', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=5)),
                ('custumer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='content.Product')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.SubCategory'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr', to='content.SubCategory'),
        ),
    ]
