# Generated by Django 3.0.8 on 2020-08-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200803_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat_Attr',
            new_name='Product_Attr',
        ),
    ]
