# Generated by Django 3.0.8 on 2020-08-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200804_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('INT', 'Integer'), ('TXT', 'Text'), ('BOOL', 'Bool')], max_length=4)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, max_length=250, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Attribute')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Product')),
            ],
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='inner_sub_id',
            new_name='parent_category',
        ),
        migrations.DeleteModel(
            name='Product_Attr',
        ),
    ]
