# Generated by Django 3.0.8 on 2020-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_feedback_custumer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(through='content.ProductAttr', to='content.Attribute'),
        ),
    ]
