# Generated by Django 3.0.8 on 2020-08-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200813_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr', to='content.SubCategory'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='content.Product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=5),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='attr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_attr', to='content.Attribute'),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_attr', to='content.Product'),
        ),
    ]
